# GAUSS

In [1]:
import numpy as np
def gauss_elimination(matriks):
  solusi = [0,0,0]
  n = len(matriks[0])
  for i in range (0,n-1):
    if matriks[i][i] == 0:
      return
    for j in range (i+1,n-1):
      ratio = matriks[j][i]/matriks[i][i]
      for k in range (0,n):
        matriks[j][k] = matriks[j][k] - ratio*matriks[i][k]
  solusi[n-2]=matriks[n-2][n-1]/matriks[n-2][n-2]
  for i in range (n-3,-1,-1):
    solusi[i] = matriks[i][n-1]
    for j in range (i+1,n-1):
      solusi[i] = solusi[i]-matriks[i][j]*solusi[j]
    solusi[i] = solusi[i]/matriks[i][i]
  print (solusi)


In [2]:
matriks = np.array([[1,1,1,6],[1,2,-1,2],[2,1,2,10]])
gauss_elimination(matriks)

[1.0, 2.0, 3.0]


# LU DECOMPOSITION

In [3]:
import numpy as np
import scipy.linalg as la
def lu_decomp(matriks):
  print("matriks",matriks)
  P,L,U = la.lu(matriks)
  print("P",P)
  print("L",L)
  print("U",U)

In [4]:
matriks = np.array([[1,1,1],[1,2,-1],[2,1,2]])
lu_decomp(matriks)

matriks [[ 1  1  1]
 [ 1  2 -1]
 [ 2  1  2]]
P [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L [[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.5        0.33333333 1.        ]]
U [[ 2.          1.          2.        ]
 [ 0.          1.5        -2.        ]
 [ 0.          0.          0.66666667]]
